# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Burns Antiphoner
email: anna.kijas@bc.edu
description: > # this means to ignore newlines until next config item, i.e. "baseurl:"
  The fourteenth-century Burns Antiphoner, held in the collections of Boston College’s John J.
  Burns Library, is an illuminated manuscript antiphoner, a volume of monophonic chant originally
  used for singing the divine office of the Roman Catholic church.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

sass:
  style: compressed

# Ignore these files
exclude: [README.md]